// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    slug,
    description
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, slug, description
`

type CreateCategoryParams struct {
	Name        string
	Slug        string
	Description *string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const existCategoryBySlug = `-- name: ExistCategoryBySlug :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE slug = $1
) AS exist
`

func (q *Queries) ExistCategoryBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, existCategoryBySlug, slug)
	var exist bool
	err := row.Scan(&exist)
	return exist, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, description
FROM categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description
FROM categories
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description
FROM categories
ORDER BY name ASC
LIMIT $2
OFFSET $1
`

type ListCategoriesParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategories = `-- name: SearchCategories :many
SELECT id, name, slug, description
FROM categories
WHERE
    name ILIKE '%' || $1 || '%'
    OR description ILIKE '%' || $1 || '%'
ORDER BY name ASC
LIMIT  $3
OFFSET $2
`

type SearchCategoriesParams struct {
	Query      *string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, searchCategories, arg.Query, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name        = COALESCE($1, name),
    slug        = COALESCE($2, slug),
    description = COALESCE($3, description)
WHERE id = $4
RETURNING id, name, slug, description
`

type UpdateCategoryParams struct {
	Name        *string
	Slug        *string
	Description *string
	ID          uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
	)
	return i, err
}
