// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatroom_participants.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addPersonalChatroomParticipant = `-- name: AddPersonalChatroomParticipant :one
INSERT INTO chatroom_participants (chatroom_id, user_id)
VALUES ($1, $2)
RETURNING id, chatroom_id, user_id, joined_at, left_at
`

type AddPersonalChatroomParticipantParams struct {
	ChatroomID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) AddPersonalChatroomParticipant(ctx context.Context, arg AddPersonalChatroomParticipantParams) (ChatroomParticipant, error) {
	row := q.db.QueryRow(ctx, addPersonalChatroomParticipant, arg.ChatroomID, arg.UserID)
	var i ChatroomParticipant
	err := row.Scan(
		&i.ID,
		&i.ChatroomID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
