// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatrooms.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createPersonalChatroom = `-- name: CreatePersonalChatroom :one
INSERT INTO chatrooms (type, participant_key)
VALUES ('personal', $1)
RETURNING id, type, project_id, participant_key, created_at
`

func (q *Queries) CreatePersonalChatroom(ctx context.Context, participantKey *string) (Chatroom, error) {
	row := q.db.QueryRow(ctx, createPersonalChatroom, participantKey)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProjectID,
		&i.ParticipantKey,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectChatroom = `-- name: CreateProjectChatroom :one
INSERT INTO chatrooms (type, project_id)
VALUES ('project', $1)
RETURNING id, type, project_id, participant_key, created_at
`

func (q *Queries) CreateProjectChatroom(ctx context.Context, projectID uuid.UUID) (Chatroom, error) {
	row := q.db.QueryRow(ctx, createProjectChatroom, projectID)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProjectID,
		&i.ParticipantKey,
		&i.CreatedAt,
	)
	return i, err
}

const getChatroomByID = `-- name: GetChatroomByID :one
SELECT id, type, project_id, participant_key, created_at FROM chatrooms
WHERE id = $1
`

func (q *Queries) GetChatroomByID(ctx context.Context, id uuid.UUID) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroomByID, id)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProjectID,
		&i.ParticipantKey,
		&i.CreatedAt,
	)
	return i, err
}

const getChatroomByParticipantKey = `-- name: GetChatroomByParticipantKey :one
SELECT id, type, project_id, participant_key, created_at FROM chatrooms
WHERE participant_key = $1
`

func (q *Queries) GetChatroomByParticipantKey(ctx context.Context, participantKey *string) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroomByParticipantKey, participantKey)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProjectID,
		&i.ParticipantKey,
		&i.CreatedAt,
	)
	return i, err
}

const getChatroomByProjectID = `-- name: GetChatroomByProjectID :one
SELECT id, type, project_id, participant_key, created_at FROM chatrooms
WHERE project_id = $1
`

func (q *Queries) GetChatroomByProjectID(ctx context.Context, projectID uuid.UUID) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroomByProjectID, projectID)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProjectID,
		&i.ParticipantKey,
		&i.CreatedAt,
	)
	return i, err
}
