// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatroom_participants.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addPersonalChatroomParticipant = `-- name: AddPersonalChatroomParticipant :many
INSERT INTO chatroom_participants (chatroom_id, user_id)
VALUES (unnest($1::uuid[]), unnest($2::uuid[]))
RETURNING id, chatroom_id, user_id, joined_at, left_at
`

type AddPersonalChatroomParticipantParams struct {
	ChatroomID []uuid.UUID
	UserID     []uuid.UUID
}

func (q *Queries) AddPersonalChatroomParticipant(ctx context.Context, arg AddPersonalChatroomParticipantParams) ([]ChatroomParticipant, error) {
	rows, err := q.db.Query(ctx, addPersonalChatroomParticipant, arg.ChatroomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatroomParticipant
	for rows.Next() {
		var i ChatroomParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ChatroomID,
			&i.UserID,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
