// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (room_id, sender_id, text)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, room_id, sender_id, text, created_at
`

type CreateChatParams struct {
	RoomID   uuid.UUID
	SenderID uuid.UUID
	Text     *string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.RoomID, arg.SenderID, arg.Text)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats
WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatID = `-- name: GetChatID :one
SELECT
    c.id,
    c.room_id,
    c.text,
    c.created_at,
    jsonb_build_object(
        'id',              u.id,
        'full_name',       u.full_name,
        'email',           u.email,
        'gender',          u.gender,
        'profile_picture', u.profile_picture,
        'global_role',     u.global_role,
        'created_at',      u.created_at,
        'updated_at',      u.updated_at
    ) AS sender,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'id',         cm.id,
                'file_name',  cm.file_name,
                'media_type', cm.media_type,
                'size',       cm.size,
                'created_at', cm.created_at
            )
        ) FILTER (WHERE cm.id IS NOT NULL),
        '[]'::jsonb
    )::jsonb AS medias
FROM chats c
LEFT JOIN users u
    ON u.id = c.sender_id
   AND u.deleted_at IS NULL
LEFT JOIN chat_medias cm
    ON cm.chat_id = c.id
WHERE c.id = $1
GROUP BY
    c.id,
    c.room_id,
    c.text,
    c.created_at,
    u.id,
    u.full_name,
    u.email,
    u.gender,
    u.profile_picture,
    u.global_role,
    u.created_at,
    u.updated_at
ORDER BY c.created_at ASC
`

type GetChatIDRow struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Text      *string
	CreatedAt time.Time
	Sender    []byte
	Medias    []byte
}

func (q *Queries) GetChatID(ctx context.Context, id uuid.UUID) (GetChatIDRow, error) {
	row := q.db.QueryRow(ctx, getChatID, id)
	var i GetChatIDRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Text,
		&i.CreatedAt,
		&i.Sender,
		&i.Medias,
	)
	return i, err
}

const getChatsByRoomID = `-- name: GetChatsByRoomID :many
SELECT
    c.id,
    c.room_id,
    c.text,
    c.created_at,
    jsonb_build_object(
        'id',              u.id,
        'full_name',       u.full_name,
        'email',           u.email,
        'gender',          u.gender,
        'profile_picture', u.profile_picture,
        'global_role',     u.global_role,
        'created_at',      u.created_at,
        'updated_at',      u.updated_at
    ) AS sender,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'id',         cm.id,
                'file_name',  cm.file_name,
                'media_type', cm.media_type,
                'size',       cm.size,
                'created_at', cm.created_at
            )
        ) FILTER (WHERE cm.id IS NOT NULL),
        '[]'::jsonb
    )::jsonb AS medias
FROM chats c
LEFT JOIN users u
    ON u.id = c.sender_id
   AND u.deleted_at IS NULL
LEFT JOIN chat_medias cm
    ON cm.chat_id = c.id
WHERE c.room_id = $1
GROUP BY
    c.id,
    c.room_id,
    c.text,
    c.created_at,
    u.id,
    u.full_name,
    u.email,
    u.gender,
    u.profile_picture,
    u.global_role,
    u.created_at,
    u.updated_at
ORDER BY c.created_at ASC
`

type GetChatsByRoomIDRow struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Text      *string
	CreatedAt time.Time
	Sender    []byte
	Medias    []byte
}

func (q *Queries) GetChatsByRoomID(ctx context.Context, roomID uuid.UUID) ([]GetChatsByRoomIDRow, error) {
	rows, err := q.db.Query(ctx, getChatsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatsByRoomIDRow
	for rows.Next() {
		var i GetChatsByRoomIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Text,
			&i.CreatedAt,
			&i.Sender,
			&i.Medias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestChatPreview = `-- name: GetLatestChatPreview :many
SELECT 
    cr.id   AS chatroom_id,
    cr.type AS type,
    lc.created_at AS last_message_at,

    -- Nama: Ambil dari nama project atau nama user lawan bicara
    (CASE 
        WHEN cr.type = 'project' THEN p.name 
        ELSE u.full_name 
    END)::text AS name,

    -- Avatar: Ambil profile picture user lawan (untuk personal)
    (CASE 
        WHEN cr.type = 'personal' THEN u.profile_picture 
        ELSE NULL 
    END)::text AS avatar,

    -- Preview pesan terakhir
    COALESCE(
        lc.text, 
        CASE 
            WHEN has_media.exists THEN '[media]' 
            ELSE '' 
        END
    )::text AS last_message

FROM chatrooms cr


LEFT JOIN projects p 
    ON cr.type = 'project' AND cr.project_id = p.id

LEFT JOIN LATERAL (
    SELECT 
        u.full_name,
        u.profile_picture
    FROM chatroom_participants cp_other
    JOIN users u ON u.id = cp_other.user_id
    WHERE cp_other.chatroom_id = cr.id
      AND cp_other.user_id != $1
      AND cp_other.left_at IS NULL
    LIMIT 1
) u ON cr.type = 'personal'

LEFT JOIN LATERAL (
    SELECT id, text, created_at
    FROM chats c
    WHERE c.room_id = cr.id
    ORDER BY c.created_at DESC
    LIMIT 1
) lc ON TRUE

LEFT JOIN LATERAL (
    SELECT EXISTS (
        SELECT 1 FROM chat_medias cm 
        WHERE cm.chat_id = lc.id
    ) AS exists
) has_media ON lc.id IS NOT NULL

WHERE (
    (cr.type = 'project' AND EXISTS (
        SELECT 1 FROM project_members pm 
        WHERE pm.project_id = cr.project_id 
          AND pm.user_id = $1 
          AND pm.left_at IS NULL
    ))
    OR 
    (cr.type = 'personal' AND EXISTS (
        SELECT 1 FROM chatroom_participants cp 
        WHERE cp.chatroom_id = cr.id 
          AND cp.user_id = $1 
          AND cp.left_at IS NULL
    ))
)

ORDER BY lc.created_at DESC NULLS LAST
`

type GetLatestChatPreviewRow struct {
	ChatroomID    uuid.UUID
	Type          string
	LastMessageAt time.Time
	Name          string
	Avatar        string
	LastMessage   string
}

// SEMUA JOIN HARUS DI SINI (SEBELUM WHERE)
// 1. Ambil detail Project jika tipenya project
// 2. Ambil detail User Lawan jika tipenya personal
// 3. Ambil chat terakhir
// 4. Cek apakah ada media di chat terakhir tersebut
// KLAUSA WHERE SETELAH SEMUA JOIN SELESAI
func (q *Queries) GetLatestChatPreview(ctx context.Context, currentUserID uuid.UUID) ([]GetLatestChatPreviewRow, error) {
	rows, err := q.db.Query(ctx, getLatestChatPreview, currentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestChatPreviewRow
	for rows.Next() {
		var i GetLatestChatPreviewRow
		if err := rows.Scan(
			&i.ChatroomID,
			&i.Type,
			&i.LastMessageAt,
			&i.Name,
			&i.Avatar,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
