// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_media.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createChatMedia = `-- name: CreateChatMedia :many
INSERT INTO chat_medias (chat_id, file_name, media_type)
VALUES (
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::chat_media_type[])
)
RETURNING id, chat_id, file_name, media_type, size, created_at
`

type CreateChatMediaParams struct {
	ChatID    []uuid.UUID
	Filename  []string
	MediaType []string
}

func (q *Queries) CreateChatMedia(ctx context.Context, arg CreateChatMediaParams) ([]ChatMedia, error) {
	rows, err := q.db.Query(ctx, createChatMedia, arg.ChatID, arg.Filename, arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMedia
	for rows.Next() {
		var i ChatMedia
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.FileName,
			&i.MediaType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMediasByChatID = `-- name: GetChatMediasByChatID :many
SELECT
    cm.id,
    cm.chat_id,
    cm.file_name,
    cm.media_type,
    cm.size,
    cm.created_at
FROM chat_medias cm
WHERE cm.chat_id = $1
`

func (q *Queries) GetChatMediasByChatID(ctx context.Context, chatID uuid.UUID) ([]ChatMedia, error) {
	rows, err := q.db.Query(ctx, getChatMediasByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMedia
	for rows.Next() {
		var i ChatMedia
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.FileName,
			&i.MediaType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMediasByRoomID = `-- name: GetChatMediasByRoomID :many
SELECT
    cm.id,
    cm.chat_id,
    cm.file_name,
    cm.media_type,
    cm.size,
    cm.created_at
FROM chat_medias cm
JOIN chats c
    ON c.id = cm.chat_id
WHERE c.room_id = $1
ORDER BY cm.created_at DESC
`

func (q *Queries) GetChatMediasByRoomID(ctx context.Context, roomID uuid.UUID) ([]ChatMedia, error) {
	rows, err := q.db.Query(ctx, getChatMediasByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMedia
	for rows.Next() {
		var i ChatMedia
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.FileName,
			&i.MediaType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
