// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    product_id,
    ordered_price
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, product_id, ordered_price, status, created_at, updated_at, deleted_at
`

type CreateOrderParams struct {
	UserID       uuid.UUID
	ProductID    uuid.UUID
	OrderedPrice float64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.ProductID, arg.OrderedPrice)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OrderedPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT 
    o.id, o.user_id, o.product_id, o.ordered_price, o.status, o.created_at, o.updated_at, o.deleted_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at 
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.id = o.product_id
WHERE o.id = $1
  AND o.deleted_at IS NULL
`

type GetOrderByIDRow struct {
	Order   Order
	User    User
	Product Product
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.Order.ID,
		&i.Order.UserID,
		&i.Order.ProductID,
		&i.Order.OrderedPrice,
		&i.Order.Status,
		&i.Order.CreatedAt,
		&i.Order.UpdatedAt,
		&i.Order.DeletedAt,
		&i.User.ID,
		&i.User.GlobalRole,
		&i.User.FullName,
		&i.User.Email,
		&i.User.PhoneNumber,
		&i.User.ProfilePicture,
		&i.User.Gender,
		&i.User.Provider,
		&i.User.ProviderUserID,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.Product.ID,
		&i.Product.Name,
		&i.Product.Slug,
		&i.Product.Description,
		&i.Product.Price,
		&i.Product.Status,
		&i.Product.IsFeatured,
		&i.Product.CreatedAt,
		&i.Product.UpdatedAt,
		&i.Product.DeletedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT 
    o.id, o.user_id, o.product_id, o.ordered_price, o.status, o.created_at, o.updated_at, o.deleted_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at 
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.id = o.product_id
WHERE (
   $1::text IS NULL 
   OR $1::text = ''
   OR o.status = $1::order_status_enum
)
AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
`

type ListOrdersRow struct {
	Order   Order
	User    User
	Product Product
}

func (q *Queries) ListOrders(ctx context.Context, status *string) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.UserID,
			&i.Order.ProductID,
			&i.Order.OrderedPrice,
			&i.Order.Status,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.DeletedAt,
			&i.User.ID,
			&i.User.GlobalRole,
			&i.User.FullName,
			&i.User.Email,
			&i.User.PhoneNumber,
			&i.User.ProfilePicture,
			&i.User.Gender,
			&i.User.Provider,
			&i.User.ProviderUserID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.Product.ID,
			&i.Product.Name,
			&i.Product.Slug,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Status,
			&i.Product.IsFeatured,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Product.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT 
    o.id, o.user_id, o.product_id, o.ordered_price, o.status, o.created_at, o.updated_at, o.deleted_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at 
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.id = o.product_id
WHERE o.user_id = $1
  AND (
    $2::text IS NULL 
    OR $2::text = ''
    OR o.status = $2::order_status_enum
  )
  AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Status *string
}

type ListOrdersByUserRow struct {
	Order   Order
	User    User
	Product Product
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserRow
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.UserID,
			&i.Order.ProductID,
			&i.Order.OrderedPrice,
			&i.Order.Status,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.DeletedAt,
			&i.User.ID,
			&i.User.GlobalRole,
			&i.User.FullName,
			&i.User.Email,
			&i.User.PhoneNumber,
			&i.User.ProfilePicture,
			&i.User.Gender,
			&i.User.Provider,
			&i.User.ProviderUserID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.Product.ID,
			&i.Product.Name,
			&i.Product.Slug,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Status,
			&i.Product.IsFeatured,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Product.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrder = `-- name: SoftDeleteOrder :execrows
UPDATE orders
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, product_id, ordered_price, status, created_at, updated_at, deleted_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OrderedPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
