// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewPayment = `-- name: CreateNewPayment :one
INSERT INTO payments (
    order_id,
    method,
    amount
) VALUES (
    $1, $2, $3
) RETURNING id, order_id, method, status, amount, fee, total_payment, payment_number, expired_at, paid_at, created_at, deleted_at
`

type CreateNewPaymentParams struct {
	OrderID uuid.UUID
	Method  *string
	Amount  float64
}

func (q *Queries) CreateNewPayment(ctx context.Context, arg CreateNewPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createNewPayment, arg.OrderID, arg.Method, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT p.id, p.order_id, p.method, p.status, p.amount, p.fee, p.total_payment, p.payment_number, p.expired_at, p.paid_at, p.created_at, p.deleted_at FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.user_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
`

func (q *Queries) GetAllPayments(ctx context.Context, userID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getAllPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Method,
			&i.Status,
			&i.Amount,
			&i.Fee,
			&i.TotalPayment,
			&i.PaymentNumber,
			&i.ExpiredAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPayment = `-- name: GetLatestPayment :one
SELECT p.id, p.order_id, p.method, p.status, p.amount, p.fee, p.total_payment, p.payment_number, p.expired_at, p.paid_at, p.created_at, p.deleted_at FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.user_id = $1 
  AND p.order_id = $2
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC 
LIMIT 1
`

type GetLatestPaymentParams struct {
	UserID  uuid.UUID
	OrderID uuid.UUID
}

func (q *Queries) GetLatestPayment(ctx context.Context, arg GetLatestPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getLatestPayment, arg.UserID, arg.OrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentById = `-- name: GetPaymentById :one
SELECT p.id, p.order_id, p.method, p.status, p.amount, p.fee, p.total_payment, p.payment_number, p.expired_at, p.paid_at, p.created_at, p.deleted_at FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE p.id = $1 
  AND o.user_id = $2
  AND p.deleted_at IS NULL
LIMIT 1
`

type GetPaymentByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPaymentById(ctx context.Context, arg GetPaymentByIdParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentById, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setPaymentCancelled = `-- name: SetPaymentCancelled :one
UPDATE payments
SET
    status = 'cancelled'
WHERE id = $1
RETURNING id, order_id, method, status, amount, fee, total_payment, payment_number, expired_at, paid_at, created_at, deleted_at
`

func (q *Queries) SetPaymentCancelled(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentCancelled, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setPaymentExpired = `-- name: SetPaymentExpired :exec
UPDATE payments 
SET 
    status = 'expired'
WHERE id = $1
`

func (q *Queries) SetPaymentExpired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPaymentExpired, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
    status = $2,
    paid_at = $3
WHERE id = $1
RETURNING id, order_id, method, status, amount, fee, total_payment, payment_number, expired_at, paid_at, created_at, deleted_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
	PaidAt *time.Time
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.PaidAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePaymentWithGatewayData = `-- name: UpdatePaymentWithGatewayData :one
UPDATE payments 
SET 
    fee = $2,
    total_payment = $3,
    payment_number = $4,
    expired_at = $5
WHERE id = $1
RETURNING id, order_id, method, status, amount, fee, total_payment, payment_number, expired_at, paid_at, created_at, deleted_at
`

type UpdatePaymentWithGatewayDataParams struct {
	ID            uuid.UUID
	Fee           *float64
	TotalPayment  *float64
	PaymentNumber *string
	ExpiredAt     *time.Time
}

func (q *Queries) UpdatePaymentWithGatewayData(ctx context.Context, arg UpdatePaymentWithGatewayDataParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentWithGatewayData,
		arg.ID,
		arg.Fee,
		arg.TotalPayment,
		arg.PaymentNumber,
		arg.ExpiredAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.Fee,
		&i.TotalPayment,
		&i.PaymentNumber,
		&i.ExpiredAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
