// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const checkProductSlugExists = `-- name: CheckProductSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM products 
    WHERE slug = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckProductSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, checkProductSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(
    name,slug,description,price,status,is_featured
) VALUES(
    $1,$2,$3,$4,$5,$6
)
RETURNING id, name, slug, description, price, status, is_featured, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	Name        string
	Slug        string
	Description *string
	Price       float64
	Status      string
	IsFeatured  bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.IsFeatured,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProduct = `-- name: GetAllProduct :many
SELECT id, name, slug, description, price, status, is_featured, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllProduct(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT id, name, slug, description, price, status, is_featured, created_at, updated_at, deleted_at FROM products 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, description, price, status, is_featured, created_at, updated_at, deleted_at FROM products 
WHERE slug = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    price = COALESCE($5, price),
    status = COALESCE($6, status),
    is_featured = COALESCE($7, is_featured),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, description, price, status, is_featured, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        *string
	Slug        *string
	Description *string
	Price       *float64
	Status      interface{}
	IsFeatured  *bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.IsFeatured,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
