// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createProgress = `-- name: CreateProgress :one
INSERT INTO progresses (
    project_id,
    title,
    weight
) VALUES (
    $1, $2, $3
)
RETURNING id, project_id, project_member_id, title, weight, is_completed, created_at
`

type CreateProgressParams struct {
	ProjectID uuid.UUID
	Title     string
	Weight    float64
}

func (q *Queries) CreateProgress(ctx context.Context, arg CreateProgressParams) (Progress, error) {
	row := q.db.QueryRow(ctx, createProgress, arg.ProjectID, arg.Title, arg.Weight)
	var i Progress
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectMemberID,
		&i.Title,
		&i.Weight,
		&i.IsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProgress = `-- name: DeleteProgress :exec
DELETE FROM progresses
WHERE id         = $1
  AND project_id = $2
`

type DeleteProgressParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteProgress(ctx context.Context, arg DeleteProgressParams) error {
	_, err := q.db.Exec(ctx, deleteProgress, arg.ID, arg.ProjectID)
	return err
}

const getProgressesByProject = `-- name: GetProgressesByProject :many
SELECT id, project_id, project_member_id, title, weight, is_completed, created_at
FROM progresses
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetProgressesByProject(ctx context.Context, projectID uuid.UUID) ([]Progress, error) {
	rows, err := q.db.Query(ctx, getProgressesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Progress
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectMemberID,
			&i.Title,
			&i.Weight,
			&i.IsCompleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalWeightByProject = `-- name: GetTotalWeightByProject :one
SELECT COALESCE(SUM(weight), 0)::DECIMAL(5,2) AS total_weight
FROM progresses
WHERE project_id = $1
`

// Untuk validasi di application layer agar total weight = 100
func (q *Queries) GetTotalWeightByProject(ctx context.Context, projectID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalWeightByProject, projectID)
	var total_weight float64
	err := row.Scan(&total_weight)
	return total_weight, err
}

const updateProgress = `-- name: UpdateProgress :one
UPDATE progresses
SET
    title        = COALESCE($3, title),
    weight       = COALESCE($4, weight),
    is_completed = COALESCE($5, is_completed)
WHERE id         = $1
  AND project_id = $2
RETURNING id, project_id, project_member_id, title, weight, is_completed, created_at
`

type UpdateProgressParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Title       *string
	Weight      *float64
	IsCompleted *bool
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) (Progress, error) {
	row := q.db.QueryRow(ctx, updateProgress,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Weight,
		arg.IsCompleted,
	)
	var i Progress
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectMemberID,
		&i.Title,
		&i.Weight,
		&i.IsCompleted,
		&i.CreatedAt,
	)
	return i, err
}
