// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    order_id,
    name,
    description,
    status,
    allowed_revision_count,
    actual_start_date,
    end_date
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    COALESCE($5::int, 3), 
    $6, -- Gunakan narg jika start_date bisa null/tidak diisi saat create
    $7
)
RETURNING id, order_id, name, description, status, allowed_revision_count, actual_start_date, end_date, created_at, updated_at
`

type CreateProjectParams struct {
	OrderID              uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount *int32
	StartDate            *time.Time
	EndDate              *time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrderID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.AllowedRevisionCount,
		arg.StartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectDetail = `-- name: GetProjectDetail :one
SELECT
    p.id,
    p.name,
    p.description,
    p.status,
    p.allowed_revision_count,
    p.actual_start_date,
    p.end_date,
    p.created_at,
    p.updated_at,

    -- Order (tetap flat)
    o.id            AS order_id,
    o.status        AS order_status,
    o.ordered_price AS ordered_price,
    o.user_id       AS order_user_id,
    o.product_id    AS order_product_id,
    o.created_at    AS order_created_at,

    COALESCE(
        (
            SELECT JSON_AGG(JSONB_BUILD_OBJECT(
                'id', pm.id,
                'project_id', pm.project_id,
                'joined_at', pm.joined_at,
                'left_at', pm.left_at,
                'is_owner', pm.is_owner,

                'user', JSONB_BUILD_OBJECT(
                    'id', u.id,
                    'global_role', u.global_role,
                    'full_name', u.full_name,
                    'email', u.email,
                    'phone_number', u.phone_number,
                    'profile_picture', u.profile_picture,
                    'gender', u.gender,
                    'created_at', u.created_at,
                    'updated_at', u.updated_at,
                    'deleted_at', u.deleted_at
                ),

                'role', JSONB_BUILD_OBJECT(
                    'id', r.id,
                    'role_name', r.name,
                    'created_at', r.created_at
                )
            ))
            FROM project_members pm
            JOIN users u ON u.id = pm.user_id
            JOIN roles r ON r.id = pm.role_id
            WHERE pm.project_id = p.id AND pm.left_at IS NULL
        ),
        '[]'
    )::jsonb AS project_members,

    COALESCE(
        (
            SELECT JSON_AGG(JSONB_BUILD_OBJECT(
                'id', pr.id,
                'project_id', pr.project_id,
                'title', pr.title,
                'weight', pr.weight,
                'is_completed', pr.is_completed,
                'created_at', pr.created_at,

                'member', JSONB_BUILD_OBJECT(
                    'id', pm_task.id,
                    'project_id', pm_task.project_id,
                    'joined_at', pm_task.joined_at,
                    'left_at', pm_task.left_at,
                    'is_owner', pm_task.is_owner,

                    'user', JSONB_BUILD_OBJECT(
                        'id', u_task.id,
                        'global_role', u_task.global_role,
                        'full_name', u_task.full_name,
                        'email', u_task.email,
                        'phone_number', u_task.phone_number,
                        'profile_picture', u_task.profile_picture,
                        'gender', u_task.gender,
                        'created_at', u_task.created_at,
                        'updated_at', u_task.updated_at,
                        'deleted_at', u_task.deleted_at
                    ),

                    'role', JSONB_BUILD_OBJECT(
                        'id', r_task.id,
                        'role_name', r_task.name,
                        'created_at', r_task.created_at
                    )
                )
            ))
            FROM progresses pr
            JOIN project_members pm_task ON pm_task.id = pr.project_member_id
            JOIN users u_task ON u_task.id = pm_task.user_id
            JOIN roles r_task ON r_task.id = pm_task.role_id
            WHERE pr.project_id = p.id
        ),
        '[]'
    )::jsonb AS progress,

    COALESCE(
        (
            SELECT JSON_AGG(JSONB_BUILD_OBJECT(
                'id', rv.id,
                'title', rv.title,
                'reason', rv.reason,
                'status', rv.status,
                'created_at', rv.created_at
            ))
            FROM revision_requests rv
            WHERE rv.project_id = p.id
        ),
        '[]'
    )::jsonb AS revisions

FROM projects p
JOIN orders o ON o.id = p.order_id

WHERE p.id = $1
`

type GetProjectDetailRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	OrderID              uuid.UUID
	OrderStatus          string
	OrderedPrice         float64
	OrderUserID          uuid.UUID
	OrderProductID       uuid.UUID
	OrderCreatedAt       time.Time
	ProjectMembers       []byte
	Progress             []byte
	Revisions            []byte
}

// ---------------------------------------------------------------
// GET DETAIL PROJECT
// Join: orders, project_members -> users -> roles,
//
//	progresses, revision_requests
//
// Members filter: hanya yang left_at IS NULL
// ---------------------------------------------------------------
func (q *Queries) GetProjectDetail(ctx context.Context, id uuid.UUID) (GetProjectDetailRow, error) {
	row := q.db.QueryRow(ctx, getProjectDetail, id)
	var i GetProjectDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.OrderStatus,
		&i.OrderedPrice,
		&i.OrderUserID,
		&i.OrderProductID,
		&i.OrderCreatedAt,
		&i.ProjectMembers,
		&i.Progress,
		&i.Revisions,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.order_id,
    p.name,
    p.description,
    p.status,
    p.allowed_revision_count,
    p.actual_start_date,
    p.end_date,
    p.created_at,
    p.updated_at,

    -- Project Members
    COALESCE(
        (
            SELECT JSON_AGG(JSONB_BUILD_OBJECT(
                'id', pm.id,
                'project_id', pm.project_id,
                'joined_at', pm.joined_at,
                'left_at', pm.left_at,
                'is_owner', pm.is_owner,

                'user', JSONB_BUILD_OBJECT(
                    'id', u.id,
                    'global_role', u.global_role,
                    'full_name', u.full_name,
                    'email', u.email,
                    'phone_number', u.phone_number,
                    'profile_picture', u.profile_picture,
                    'gender', u.gender,
                    'created_at', u.created_at,
                    'updated_at', u.updated_at,
                    'deleted_at', u.deleted_at
                ),

                'role', JSONB_BUILD_OBJECT(
                    'id', r.id,
                    'role_name', r.name,
                    'created_at', r.created_at
                )
            ))
            FROM project_members pm
            JOIN users u ON u.id = pm.user_id
            JOIN roles r ON r.id = pm.role_id
            WHERE pm.project_id = p.id AND pm.left_at IS NULL
        ),
        '[]'
    )::jsonb AS project_members,

    -- Progress
    COALESCE(
        (
            SELECT JSON_AGG(JSONB_BUILD_OBJECT(
                'id', pr.id,
                'project_id', pr.project_id,
                'title', pr.title,
                'weight', pr.weight,
                'is_completed', pr.is_completed,
                'created_at', pr.created_at,

                'member', JSONB_BUILD_OBJECT(
                    'id', pm_task.id,
                    'project_id', pm_task.project_id,
                    'joined_at', pm_task.joined_at,
                    'left_at', pm_task.left_at,
                    'is_owner', pm_task.is_owner,

                    'user', JSONB_BUILD_OBJECT(
                        'id', u_task.id,
                        'global_role', u_task.global_role,
                        'full_name', u_task.full_name,
                        'email', u_task.email,
                        'phone_number', u_task.phone_number,
                        'profile_picture', u_task.profile_picture,
                        'gender', u_task.gender,
                        'created_at', u_task.created_at,
                        'updated_at', u_task.updated_at,
                        'deleted_at', u_task.deleted_at
                    ),

                    'role', JSONB_BUILD_OBJECT(
                        'id', r_task.id,
                        'role_name', r_task.name,
                        'created_at', r_task.created_at
                    )
                )
            ))
            FROM progresses pr
            JOIN project_members pm_task ON pm_task.id = pr.project_member_id
            JOIN users u_task ON u_task.id = pm_task.user_id
            JOIN roles r_task ON r_task.id = pm_task.role_id
            WHERE pr.project_id = p.id
        ),
        '[]'
    )::jsonb AS progress

FROM projects p
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID                   uuid.UUID
	OrderID              uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProjectMembers       []byte
	Progress             []byte
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.AllowedRevisionCount,
			&i.ActualStartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectMembers,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name                   = COALESCE($2, name),
    description            = COALESCE($3, description),
    status                 = COALESCE($4, status),
    allowed_revision_count = COALESCE($5, allowed_revision_count),
    actual_start_date      = COALESCE($6, actual_start_date),
    end_date               = COALESCE($7, end_date),
    updated_at             = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_id, name, description, status, allowed_revision_count, actual_start_date, end_date, created_at, updated_at
`

type UpdateProjectParams struct {
	ID                   uuid.UUID
	Name                 *string
	Description          *string
	Status               interface{}
	AllowedRevisionCount *int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.AllowedRevisionCount,
		arg.ActualStartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
