// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (
    project_id,
    user_id,
    role_id,
    is_owner
) VALUES (
    $1 ,$2, $3,$4
)
RETURNING id, project_id, user_id, role_id, is_owner, joined_at, left_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
	IsOwner   bool
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.RoleID,
		arg.IsOwner,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getActiveProjectMembers = `-- name: GetActiveProjectMembers :many
SELECT 
    pm.id,
    pm.project_id,
    pm.is_owner,
    pm.joined_at,

    jsonb_build_object(
        'id', u.id,
        'full_name', u.full_name,
        'email', u.email,
        'gender', u.gender,
        'profile_picture', u.profile_picture,
        'global_role', u.global_role,
        'created_at', u.created_at,
        'updated_at', u.updated_at
    ) AS user,

     jsonb_build_object(
        'id', r.id,
        'role_name', r.name,
        'created_at', r.created_at
    ) AS role

FROM project_members pm
JOIN users u 
    ON u.id = pm.user_id
   AND u.deleted_at IS NULL

JOIN roles r 
    ON r.id = pm.role_id

WHERE pm.project_id = $1
  AND pm.left_at IS NULL

ORDER BY pm.joined_at ASC
`

type GetActiveProjectMembersRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	IsOwner   bool
	JoinedAt  time.Time
	User      []byte
	Role      []byte
}

func (q *Queries) GetActiveProjectMembers(ctx context.Context, projectID uuid.UUID) ([]GetActiveProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, getActiveProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveProjectMembersRow
	for rows.Next() {
		var i GetActiveProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IsOwner,
			&i.JoinedAt,
			&i.User,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMember = `-- name: GetAllMember :many
SELECT 
    pm.id,
    pm.project_id,
    pm.user_id,
    pm.role_id,
    pm.is_owner,
    pm.joined_at,
    pm.left_at,

    jsonb_build_object(
        'id', u.id,
        'full_name', u.full_name,
        'email', u.email,
        'gender', u.gender,
        'profile_picture', u.profile_picture,
        'global_role', u.global_role,
        'created_at', u.created_at,
        'updated_at', u.updated_at
    ) AS user,

    jsonb_build_object(
        'id', r.id,
        'role_name', r.name,
        'created_at', r.created_at
    ) AS role

FROM project_members pm
JOIN users u 
    ON u.id = pm.user_id
   AND u.deleted_at IS NULL

JOIN roles r 
    ON r.id = pm.role_id
`

type GetAllMemberRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
	IsOwner   bool
	JoinedAt  time.Time
	LeftAt    *time.Time
	User      []byte
	Role      []byte
}

func (q *Queries) GetAllMember(ctx context.Context) ([]GetAllMemberRow, error) {
	rows, err := q.db.Query(ctx, getAllMember)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMemberRow
	for rows.Next() {
		var i GetAllMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.RoleID,
			&i.IsOwner,
			&i.JoinedAt,
			&i.LeftAt,
			&i.User,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberDataByUserId = `-- name: GetMemberDataByUserId :one
SELECT 
    pm.id,
    pm.project_id,
    pm.is_owner,
    pm.joined_at,
    pm.left_at,

    jsonb_build_object(
        'id', u.id,
        'full_name', u.full_name,
        'email', u.email,
        'gender', u.gender,
        'profile_picture', u.profile_picture,
        'global_role', u.global_role,
        'created_at', u.created_at,
        'updated_at', u.updated_at
    ) AS user,

    jsonb_build_object(
        'id', r.id,
        'role_name', r.name,
        'created_at', r.created_at
    ) AS role

FROM project_members pm
JOIN users u 
    ON u.id = pm.user_id
   AND u.deleted_at IS NULL

JOIN roles r 
    ON r.id = pm.role_id

WHERE pm.user_id = $1
and pm.project_id = $2
LIMIT 1
`

type GetMemberDataByUserIdParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

type GetMemberDataByUserIdRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	IsOwner   bool
	JoinedAt  time.Time
	LeftAt    *time.Time
	User      []byte
	Role      []byte
}

func (q *Queries) GetMemberDataByUserId(ctx context.Context, arg GetMemberDataByUserIdParams) (GetMemberDataByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getMemberDataByUserId, arg.UserID, arg.ProjectID)
	var i GetMemberDataByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IsOwner,
		&i.JoinedAt,
		&i.LeftAt,
		&i.User,
		&i.Role,
	)
	return i, err
}

const getProjectMemberByID = `-- name: GetProjectMemberByID :one
SELECT 
    pm.id,
    pm.project_id,
    pm.is_owner,
    pm.joined_at,
    pm.left_at,

    jsonb_build_object(
        'id', u.id,
        'full_name', u.full_name,
        'email', u.email,
        'gender', u.gender,
        'profile_picture', u.profile_picture,
        'global_role', u.global_role,
        'created_at', u.created_at,
        'updated_at', u.updated_at
    ) AS user,

    jsonb_build_object(
        'id', r.id,
        'role_name', r.name,
        'created_at', r.created_at
    ) AS role

FROM project_members pm
JOIN users u 
    ON u.id = pm.user_id
   AND u.deleted_at IS NULL

JOIN roles r 
    ON r.id = pm.role_id

WHERE pm.id = $1
LIMIT 1
`

type GetProjectMemberByIDRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	IsOwner   bool
	JoinedAt  time.Time
	LeftAt    *time.Time
	User      []byte
	Role      []byte
}

func (q *Queries) GetProjectMemberByID(ctx context.Context, id uuid.UUID) (GetProjectMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectMemberByID, id)
	var i GetProjectMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IsOwner,
		&i.JoinedAt,
		&i.LeftAt,
		&i.User,
		&i.Role,
	)
	return i, err
}

const listProjectMembersWithUser = `-- name: ListProjectMembersWithUser :many
SELECT 
    pm.id,
    pm.project_id,
    pm.is_owner,
    pm.joined_at,
    pm.left_at,

    jsonb_build_object(
        'id', u.id,
        'full_name', u.full_name,
        'email', u.email,
        'gender', u.gender,
        'profile_picture', u.profile_picture,
        'global_role', u.global_role,
        'created_at', u.created_at,
        'updated_at', u.updated_at
    ) AS user,

    jsonb_build_object(
        'id', r.id,
        'role_name', r.name,
        'created_at', r.created_at
    ) AS role

FROM project_members pm
JOIN users u 
    ON u.id = pm.user_id
   AND u.deleted_at IS NULL

JOIN roles r 
    ON r.id = pm.role_id

WHERE pm.project_id = $1
ORDER BY pm.joined_at ASC
`

type ListProjectMembersWithUserRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	IsOwner   bool
	JoinedAt  time.Time
	LeftAt    *time.Time
	User      []byte
	Role      []byte
}

func (q *Queries) ListProjectMembersWithUser(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembersWithUser, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersWithUserRow
	for rows.Next() {
		var i ListProjectMembersWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IsOwner,
			&i.JoinedAt,
			&i.LeftAt,
			&i.User,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :one
UPDATE project_members
SET left_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND left_at IS NULL
RETURNING user_id, project_id
`

type RemoveProjectMemberRow struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, id uuid.UUID) (RemoveProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, removeProjectMember, id)
	var i RemoveProjectMemberRow
	err := row.Scan(&i.UserID, &i.ProjectID)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET 
    role_id = $1,
    is_owner =  COALESCE($2, is_owner)
WHERE id = $3
  AND left_at IS NULL
RETURNING id, project_id, user_id, role_id, is_owner, joined_at, left_at
`

type UpdateProjectMemberRoleParams struct {
	RoleID   uuid.UUID
	IsOwner  *bool
	MemberID uuid.UUID
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.RoleID, arg.IsOwner, arg.MemberID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
