// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (
    project_id,
    user_id,
    role_id
) VALUES (
    $1, $2, $3
)
RETURNING id, project_id, user_id, role_id, joined_at, left_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.RoleID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.RoleID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getActiveProjectMembers = `-- name: GetActiveProjectMembers :many
SELECT
    pm.id,
    pm.project_id,
    pm.joined_at,
    u.id             AS user_id,
    u.full_name,
    u.email,
    u.gender,
    u.profile_picture,
    r.id             AS role_id,
    r.name           AS role_name
FROM project_members pm
INNER JOIN users u ON u.id = pm.user_id
    AND u.deleted_at IS NULL
INNER JOIN roles r ON r.id = pm.role_id
WHERE pm.project_id = $1
  AND pm.left_at    IS NULL
ORDER BY pm.joined_at ASC
`

type GetActiveProjectMembersRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	JoinedAt       time.Time
	UserID         uuid.UUID
	FullName       string
	Email          string
	Gender         string
	ProfilePicture *string
	RoleID         uuid.UUID
	RoleName       string
}

// Untuk kebutuhan internal (cek member aktif, validasi, dsb)
func (q *Queries) GetActiveProjectMembers(ctx context.Context, projectID uuid.UUID) ([]GetActiveProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, getActiveProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveProjectMembersRow
	for rows.Next() {
		var i GetActiveProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JoinedAt,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.Gender,
			&i.ProfilePicture,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
UPDATE project_members
SET left_at = CURRENT_TIMESTAMP
WHERE project_id = $1
  AND user_id    = $2
  AND left_at IS NULL
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}
