// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    order_id,
    name,
    description,
    status,
    allowed_revision_count,
    actual_start_date,
    end_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_id, name, description, status, allowed_revision_count, actual_start_date, end_date, created_at, updated_at
`

type CreateProjectParams struct {
	OrderID              uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrderID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.AllowedRevisionCount,
		arg.ActualStartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectDetail = `-- name: GetProjectDetail :one
SELECT
    p.id,
    p.name,
    p.description,
    p.status,
    p.allowed_revision_count,
    p.actual_start_date,
    p.end_date,
    p.created_at,
    p.updated_at,

    -- Order info (flat columns, bukan nested — lebih predictable di scan)
    o.id            AS order_id,
    o.status        AS order_status,
    o.ordered_price AS ordered_price,
    o.user_id       AS order_user_id,
    o.product_id    AS order_product_id,
    o.created_at    AS order_created_at,

    -- Members
    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id',              pm.id,
                'user_id',         u.id,
                'full_name',       u.full_name,
                'email',           u.email,
                'gender',          u.gender,
                'profile_picture', u.profile_picture,
                'role_id',         r.id,
                'role_name',       r.name,
                'joined_at',       pm.joined_at
            )
        ) FILTER (WHERE pm.id IS NOT NULL),
        '[]'
    )::jsonb AS members,

    -- Progresses
    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id',           pr.id,
                'title',        pr.title,
                'weight',       pr.weight,
                'is_completed', pr.is_completed,
                'created_at',   pr.created_at
            )
        ) FILTER (WHERE pr.id IS NOT NULL),
        '[]'
    )::jsonb AS progresses,

    -- Revision requests
    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id',         rv.id,
                'title',      rv.title,
                'reason',     rv.reason,
                'status',     rv.status,
                'created_at', rv.created_at
            )
        ) FILTER (WHERE rv.id IS NOT NULL),
        '[]'
    )::jsonb AS revisions

FROM projects p

INNER JOIN orders o ON o.id = p.order_id

LEFT JOIN project_members pm ON pm.project_id = p.id
    AND pm.left_at IS NULL

LEFT JOIN users u ON u.id = pm.user_id
    AND u.deleted_at IS NULL

LEFT JOIN roles r ON r.id = pm.role_id

LEFT JOIN progresses pr ON pr.project_id = p.id

LEFT JOIN revision_requests rv ON rv.project_id = p.id

WHERE p.id = $1

GROUP BY
    p.id,
    o.id,
    o.status,
    o.ordered_price,
    o.user_id,
    o.product_id,
    o.created_at
`

type GetProjectDetailRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	OrderID              uuid.UUID
	OrderStatus          string
	OrderedPrice         float64
	OrderUserID          uuid.UUID
	OrderProductID       uuid.UUID
	OrderCreatedAt       time.Time
	Members              []byte
	Progresses           []byte
	Revisions            []byte
}

// ---------------------------------------------------------------
// GET DETAIL PROJECT
// Join: orders, project_members -> users -> roles,
//
//	progresses, revision_requests
//
// Members filter: hanya yang left_at IS NULL
// ---------------------------------------------------------------
func (q *Queries) GetProjectDetail(ctx context.Context, id uuid.UUID) (GetProjectDetailRow, error) {
	row := q.db.QueryRow(ctx, getProjectDetail, id)
	var i GetProjectDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.OrderStatus,
		&i.OrderedPrice,
		&i.OrderUserID,
		&i.OrderProductID,
		&i.OrderCreatedAt,
		&i.Members,
		&i.Progresses,
		&i.Revisions,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.name,
    p.description,
    p.status,
    p.allowed_revision_count,
    p.actual_start_date,
    p.end_date,
    p.created_at,
    p.updated_at,

    -- Members: JSON array of active members with user & role info
    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id',              pm.id,
                'user_id',         u.id,
                'full_name',       u.full_name,
                'email',           u.email,
                'gender',          u.gender,
                'profile_picture', u.profile_picture,
                'role_id',         r.id,
                'role_name',       r.name,
                'joined_at',       pm.joined_at
            )
        ) FILTER (WHERE pm.id IS NOT NULL),
        '[]'
    )::jsonb AS members,

    -- Progresses: JSON array
    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id',           pr.id,
                'title',        pr.title,
                'weight',       pr.weight,
                'is_completed', pr.is_completed,
                'created_at',   pr.created_at
            )
        ) FILTER (WHERE pr.id IS NOT NULL),
        '[]'
    )::jsonb AS progresses

FROM projects p

LEFT JOIN project_members pm ON pm.project_id = p.id
    AND pm.left_at IS NULL

LEFT JOIN users u  ON u.id  = pm.user_id
    AND u.deleted_at IS NULL

LEFT JOIN roles r  ON r.id  = pm.role_id

LEFT JOIN progresses pr ON pr.project_id = p.id

GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          *string
	Status               string
	AllowedRevisionCount int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Members              []byte
	Progresses           []byte
}

// ---------------------------------------------------------------
// GET LIST PROJECTS
// Join: project_members -> users -> roles, progresses
// Members filter: hanya yang left_at IS NULL (masih aktif)
// ---------------------------------------------------------------
func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.AllowedRevisionCount,
			&i.ActualStartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Members,
			&i.Progresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name                   = COALESCE($2, name),
    description            = COALESCE($3, description),
    status                 = COALESCE($4, status),
    allowed_revision_count = COALESCE($5, allowed_revision_count),
    actual_start_date      = COALESCE($6, actual_start_date),
    end_date               = COALESCE($7, end_date),
    updated_at             = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_id, name, description, status, allowed_revision_count, actual_start_date, end_date, created_at, updated_at
`

type UpdateProjectParams struct {
	ID                   uuid.UUID
	Name                 *string
	Description          *string
	Status               interface{}
	AllowedRevisionCount *int32
	ActualStartDate      *time.Time
	EndDate              *time.Time
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.AllowedRevisionCount,
		arg.ActualStartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.AllowedRevisionCount,
		&i.ActualStartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
