// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    user_id,
    product_id,
    order_id,
    rating,
    comment,
    show
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, product_id, order_id, rating, comment, show, created_at, updated_at
`

type CreateReviewParams struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
	OrderID   uuid.UUID
	Rating    int32
	Comment   *string
	Show      bool
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.ProductID,
		arg.OrderID,
		arg.Rating,
		arg.Comment,
		arg.Show,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OrderID,
		&i.Rating,
		&i.Comment,
		&i.Show,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByOrderID = `-- name: GetReviewByOrderID :one
SELECT id, user_id, product_id, order_id, rating, comment, show, created_at, updated_at FROM reviews
WHERE order_id = $1
`

func (q *Queries) GetReviewByOrderID(ctx context.Context, orderID uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByOrderID, orderID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OrderID,
		&i.Rating,
		&i.Comment,
		&i.Show,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReviewsForAdmin = `-- name: ListAllReviewsForAdmin :many
SELECT 
    r.id, r.user_id, r.product_id, r.order_id, r.rating, r.comment, r.show, r.created_at, r.updated_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at
FROM reviews r
JOIN users u ON u.id = r.user_id
JOIN products p ON p.id = r.product_id
ORDER BY r.created_at DESC
`

type ListAllReviewsForAdminRow struct {
	Review  Review
	User    User
	Product Product
}

func (q *Queries) ListAllReviewsForAdmin(ctx context.Context) ([]ListAllReviewsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllReviewsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewsForAdminRow
	for rows.Next() {
		var i ListAllReviewsForAdminRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.ProductID,
			&i.Review.OrderID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.Show,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.User.ID,
			&i.User.GlobalRole,
			&i.User.FullName,
			&i.User.Email,
			&i.User.PhoneNumber,
			&i.User.ProfilePicture,
			&i.User.Gender,
			&i.User.Provider,
			&i.User.ProviderUserID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.Product.ID,
			&i.Product.Name,
			&i.Product.Slug,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Status,
			&i.Product.IsFeatured,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Product.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedReviews = `-- name: ListFeaturedReviews :many
SELECT 
    r.id, r.user_id, r.product_id, r.order_id, r.rating, r.comment, r.show, r.created_at, r.updated_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at
FROM reviews r
JOIN users u ON u.id = r.user_id
JOIN products p ON p.id = r.product_id
WHERE r.show = TRUE
ORDER BY r.rating DESC, r.created_at DESC
LIMIT $1
`

type ListFeaturedReviewsRow struct {
	Review  Review
	User    User
	Product Product
}

func (q *Queries) ListFeaturedReviews(ctx context.Context, limit int32) ([]ListFeaturedReviewsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturedReviewsRow
	for rows.Next() {
		var i ListFeaturedReviewsRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.ProductID,
			&i.Review.OrderID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.Show,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.User.ID,
			&i.User.GlobalRole,
			&i.User.FullName,
			&i.User.Email,
			&i.User.PhoneNumber,
			&i.User.ProfilePicture,
			&i.User.Gender,
			&i.User.Provider,
			&i.User.ProviderUserID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.Product.ID,
			&i.Product.Name,
			&i.Product.Slug,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Status,
			&i.Product.IsFeatured,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Product.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT 
    r.id, r.user_id, r.product_id, r.order_id, r.rating, r.comment, r.show, r.created_at, r.updated_at,
    u.id, u.global_role, u.full_name, u.email, u.phone_number, u.profile_picture, u.gender, u.provider, u.provider_user_id, u.created_at, u.updated_at, u.deleted_at
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE r.product_id = $1
  AND r.show = TRUE
ORDER BY r.created_at DESC
`

type ListReviewsByProductRow struct {
	Review Review
	User   User
}

func (q *Queries) ListReviewsByProduct(ctx context.Context, productID uuid.UUID) ([]ListReviewsByProductRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByProductRow
	for rows.Next() {
		var i ListReviewsByProductRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.ProductID,
			&i.Review.OrderID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.Show,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.User.ID,
			&i.User.GlobalRole,
			&i.User.FullName,
			&i.User.Email,
			&i.User.PhoneNumber,
			&i.User.ProfilePicture,
			&i.User.Gender,
			&i.User.Provider,
			&i.User.ProviderUserID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT
    r.id, r.user_id, r.product_id, r.order_id, r.rating, r.comment, r.show, r.created_at, r.updated_at,
    p.id, p.name, p.slug, p.description, p.price, p.status, p.is_featured, p.created_at, p.updated_at, p.deleted_at
FROM reviews r
JOIN products p ON p.id = r.product_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
`

type ListReviewsByUserRow struct {
	Review  Review
	Product Product
}

func (q *Queries) ListReviewsByUser(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserRow
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.ProductID,
			&i.Review.OrderID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.Show,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.Product.ID,
			&i.Product.Name,
			&i.Product.Slug,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Status,
			&i.Product.IsFeatured,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Product.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewShowStatus = `-- name: UpdateReviewShowStatus :one
UPDATE reviews
SET show = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, product_id, order_id, rating, comment, show, created_at, updated_at
`

type UpdateReviewShowStatusParams struct {
	ID   uuid.UUID
	Show bool
}

func (q *Queries) UpdateReviewShowStatus(ctx context.Context, arg UpdateReviewShowStatusParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewShowStatus, arg.ID, arg.Show)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.OrderID,
		&i.Rating,
		&i.Comment,
		&i.Show,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
