// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revision.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countPendingRevisions = `-- name: CountPendingRevisions :one
SELECT COUNT(*)::INT AS pending_count
FROM revision_requests
WHERE project_id = $1
  AND status     = 'pending'
`

func (q *Queries) CountPendingRevisions(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingRevisions, projectID)
	var pending_count int32
	err := row.Scan(&pending_count)
	return pending_count, err
}

const createRevisionRequest = `-- name: CreateRevisionRequest :one
INSERT INTO revision_requests (
    project_id,
    title,
    reason
) VALUES (
    $1, $2, $3
)
RETURNING id, project_id, title, reason, status, created_at
`

type CreateRevisionRequestParams struct {
	ProjectID uuid.UUID
	Title     string
	Reason    string
}

func (q *Queries) CreateRevisionRequest(ctx context.Context, arg CreateRevisionRequestParams) (RevisionRequest, error) {
	row := q.db.QueryRow(ctx, createRevisionRequest, arg.ProjectID, arg.Title, arg.Reason)
	var i RevisionRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionsByProject = `-- name: GetRevisionsByProject :many
SELECT id, project_id, title, reason, status, created_at
FROM revision_requests
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRevisionsByProject(ctx context.Context, projectID uuid.UUID) ([]RevisionRequest, error) {
	rows, err := q.db.Query(ctx, getRevisionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionRequest
	for rows.Next() {
		var i RevisionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRevisionStatus = `-- name: UpdateRevisionStatus :one
UPDATE revision_requests
SET 
    status = COALESCE($2, status)
WHERE id   = $1
RETURNING id, project_id, title, reason, status, created_at
`

type UpdateRevisionStatusParams struct {
	ID     uuid.UUID
	Status NullRevisionStatusEnum
}

func (q *Queries) UpdateRevisionStatus(ctx context.Context, arg UpdateRevisionStatusParams) (RevisionRequest, error) {
	row := q.db.QueryRow(ctx, updateRevisionStatus, arg.ID, arg.Status)
	var i RevisionRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
