// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    email,
    profile_picture,
    provider,
    provider_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FullName       string
	Email          string
	ProfilePicture *string
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.ProfilePicture,
		arg.Provider,
		arg.ProviderUserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAuthInfoByProviderID = `-- name: GetUserAuthInfoByProviderID :one
SELECT 
    id,
    global_role
FROM users
WHERE provider = $1
  AND provider_user_id = $2
LIMIT 1
`

type GetUserAuthInfoByProviderIDParams struct {
	Provider       string
	ProviderUserID string
}

type GetUserAuthInfoByProviderIDRow struct {
	ID         uuid.UUID
	GlobalRole string
}

func (q *Queries) GetUserAuthInfoByProviderID(ctx context.Context, arg GetUserAuthInfoByProviderIDParams) (GetUserAuthInfoByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthInfoByProviderID, arg.Provider, arg.ProviderUserID)
	var i GetUserAuthInfoByProviderIDRow
	err := row.Scan(&i.ID, &i.GlobalRole)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at FROM users
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type ListUsersParams struct {
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GlobalRole,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.ProfilePicture,
			&i.Gender,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND (
    full_name    ILIKE '%' || $1 || '%'
    OR email     ILIKE '%' || $1 || '%'
    OR phone_number ILIKE '%' || $1 || '%'
  )
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type SearchUsersParams struct {
	Keyword   *string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Keyword, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GlobalRole,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.ProfilePicture,
			&i.Gender,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name       = COALESCE($1,      full_name),
    gender          = COALESCE($2, gender),
    phone_number    = COALESCE($3, phone_number),
    updated_at      = CURRENT_TIMESTAMP
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	FullName    *string
	Gender      interface{}
	PhoneNumber *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Gender,
		arg.PhoneNumber,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserGlobalRole = `-- name: UpdateUserGlobalRole :one
UPDATE users
SET
    global_role = $1,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, global_role, full_name, email, phone_number, profile_picture, gender, provider, provider_user_id, created_at, updated_at, deleted_at
`

type UpdateUserGlobalRoleParams struct {
	GlobalRole string
	ID         uuid.UUID
}

func (q *Queries) UpdateUserGlobalRole(ctx context.Context, arg UpdateUserGlobalRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGlobalRole, arg.GlobalRole, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GlobalRole,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.ProfilePicture,
		&i.Gender,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
